### ISSUE TITLE
Weird behaviour when refresh/load another data on RecyclerView

### ISSUE THREAD

**Issue by indrac** [akoscz/YouTubePlaylist#10]
I use your code to my app, and add spinned menu on top of recyclerview. Each menu have different value/playlist id, I successfully load the data from that API playlist. But the weird thing, when I select second/third option from spinned menu, the result of recyclerview is new data placed on bottom layout, I have to scroll it up to view the result. Any solution for this? Or why this is happen? Much appreciate for your help and thanks for the code.

**Comment by akoscz** [comment]
@indrac can you provide some code for me to look at?  Prefereably if you could link to your project so I can see all the code that is in question would be best.

Also, see which branch of the YouTubePlaylist are you using ?  I have a couple of branches with various changes.  I would recommend you to try the [data-binding](https://github.com/akoscz/YouTubePlaylist/tree/data-binding) branch or the [rx-java](https://github.com/akoscz/YouTubePlaylist/tree/rx-java) branch as those are a bit burther along than the master branch.

**Comment by indrac** [comment]
I posted my code on gist github of my 3 files, the YoutubeViewFragment.java is the main view of youtube playlist, I hardcoded it and set playlist ID value on number 1 and 2 on that spinner menu. PlaylistCardAdapter.java is same like your code, I changed a lil bit image loader to Universal Image Loader. And the last file fragment_youtubeview.xml is the layout for my YoutubeViewFragment class.

YoutubeViewFragment.java [https://gist.github.com/indrac/22fecce7119c741645d661ed105e2642](url)
PlaylistCardAdapter.java [https://gist.github.com/indrac/07faa0fcb53d83eb8a8937a747224dbf](url)
fragment_youtubeview.xml [https://gist.github.com/indrac/0518e69555000e20e3a803320e3d2aba](url)

So thanksful for your reply on this issue.

**Comment by akoscz** [comment]
@indrac  Not sure what exactly is wrong with your code.  It might have something to do with the `StatefulLayout` class that you are using.   Take a look at the recent changes I just made in the [master](https://github.com/akoscz/YouTubePlaylist/commits/master) branch.  I added support for selecting a playlist using a spinner from a list of playlist id's.  As an added bonus I also added the capability of fetching the playlist titles and updating the spinner with the playlist title data.

**Comment by indrac** [comment]
Thanks for answering my question, and finally I know what is wrong with my code. I compile and debug with my Nexus tablet, and I just have to declare this : 

`mLayoutManager = new StaggeredGridLayoutManager(resources.getInteger(R.integer.columns), StaggeredGridLayoutManager.VERTICAL);`

to my OnItemSelected inside spinner.setOnItemSelectedListener.

**Comment by akoscz** [comment]
Glad to hear you were able to figure out the issue you were facing!
