### ISSUE TITLE
Colored indicator on top left corner on thumbnail

### ISSUE THREAD

**Issue by vigneshwarn** [akoscz/YouTubePlaylist#16]
Fixed --

` // set the Picasso debug indicator only for debug builds
        Picasso.with(getActivity());`

**Comment by akoscz** [comment]
To completely remove the colored indicator even from debug builds, remove the following line from YouTubeFragment.onCreateView()
```Picasso.with(getActivity()).setIndicatorsEnabled(BuildConfig.DEBUG);```
