### ISSUE TITLE
How to put the playlist options inside the Navigation Drawer like this in the spinner

### ISSUE THREAD

**Issue by mauricioedu** [akoscz/YouTubePlaylist#20]
Type when opening the Navigation Drawer click on the playlist option and change the videos, can not understand the code

**Comment by akoscz** [comment]
which code are you having trouble understanding?   you do understand that asking a one line question is probably not going to give anyone enough information to be able to help you :)

**Comment by mauricioedu** [comment]
I wanted to put the options of videos that are being loaded inside the spinner and put inside a Navigation Drawer. Do you know how to do Akoscz?

**Comment by akoscz** [comment]
Sorry I can't help you with that.  Your question outside the scope of this example project.
