### ISSUE TITLE
The Green/Blue thing in corner?

### ISSUE THREAD

**Issue by RobertCarpvik** [akoscz/YouTubePlaylist#21]
What does it stand for and where do I remove it?

**Comment by mauricioedu** [comment]
To completely remove the colored indicator even from debug builds, remove the following line from YouTubeFragment.onCreateView()
Picasso.with(getActivity()).setIndicatorsEnabled(BuildConfig.DEBUG);

**Comment by akoscz** [comment]
Picasso utilizes two caches: disk and memory. The last resort is to load the image from the network, which is expensive and slow.

The color represents a source:

-  green (memory, best performance)
-  blue (disk, good performance)
-  red (network, worst performance).

https://futurestud.io/tutorials/picasso-cache-indicators-logging-stats

**Comment by RobertCarpvik** [comment]
Thank you so much for the answer, it makes a lot of sense! thanks again!
