### ISSUE TITLE
How to put a ProgressBar in uploading videos?

### ISSUE THREAD

**Issue by mauricioedu** [akoscz/YouTubePlaylist#22]
I want it to show a ProgressBar loading and when it loads it disappears

**Comment by akoscz** [comment]
What do you mean?  There's no uploading happening in this app.  Video metadata is being `downloaded` from YouTube and displayed in a RecyclerView.  If you take a look closely at the code you will see how it works.  Video metadata is downloaded in pages according to the YouTube Data API v3. The number of items to include in the resulting page is configurable in [GetPlaylistAsyncTask.java](https://github.com/akoscz/YouTubePlaylist/blob/master/app/src/main/java/com/akoscz/youtube/GetPlaylistAsyncTask.java) as `YOUTUBE_PLAYLIST_MAX_RESULTS`.  See documentation on how to use the YouTbue Data v3 API here https://developers.google.com/youtube/v3/docs/playlistItems/list
